import React from 'react';
import { ArrowLeft, ArrowUpRight, ChevronRight } from 'lucide-react';
import { useT } from './i18n.jsx';

// text-only posts: articles Eva published elsewhere, republished here
// without their artwork, each linking back to the original.
export const posts = [
  {
    slug: 'escaping-the-average',
    title: 'Escaping the Average',
    subtitle: 'A Creative’s AI Perspective',
    date: 'Aug 27, 2026',
    source: 'https://schole.ai/engineering-blog/escaping-the-average',
    sourceName: 'Scholé AI engineering blog',
    body: [
      'I bet many of you have tried this too. Type in the prompt. A sigh of relief. And then… a sad realization that it is not there yet.',
      'Or... is it?',
      'Sometimes I get truly impressed. But never when I know the subject inside out.',
      'Why is that? Models excel at math, solve difficult questions in physics, build new proteins and software, and are still so average in their creative outputs. Getting 70% of the way is easy, but the last 30% might take twice or four times as long.',
      'If you haven’t seen many websites before or studied them thoroughly, you might not know. But users start to feel it. Humans are outstanding at noticing patterns. Open LinkedIn. You know which posts were written by AI, right? I know. The grammar looks fine. They are well written. The images match, and you counted the fingers. It is not about em dashes. There is just something statistically average in the melody, in how the sentence is constructed, in which word is chosen next.',
      'When LLMs choose the next token, they are not deciding based on their judgment or their taste. They do mathematical calculations: What would be the most likely next token for this context? This is how neural networks work. And this is exactly what true creativity is trying to escape.',
      'Creatives are here to disagree, to push in new, surprising directions.',
      'In theory, LLMs could do this too. Creativity lies at the intersection of novel and useful. We could write algorithms to generate such outputs randomly or tune the temperature of an LLM, making its next word more random and unusual. However, models alone are still not able to predict whether an idea will work. They are not trained to be persistent, to romantically fight for their ideas. They will listen to your creative direction even if it is obviously bad. And being creative requires having a spine: taking risks and believing in them. Models cannot do it yet, and maybe that is actually for the better.',
      'One might wonder why we even need new output if the average is the average of what worked before.',
      'This has to do with how the brain treats the new. When we encounter something we have not seen before, a dopamine-producing part of the brain responds to the novelty itself, before any reward is attached to it. That signal helps decide what gets written into long-term memory and pulls us toward exploration.',
      'Novel things are attended to. Novel things are remembered. The predictable does not fire this circuit in the same way. So when your output is the most likely one, it is, quite literally, the one the brain is least primed to notice and least likely to keep.',
      'And this is no longer only a theory. Researchers at UCL and Exeter ran a controlled study with 300 writers and found that “access to generative AI made individual stories more novel and better written, while making the stories collectively more similar to one another.”',
      'Creativity went up for the person and down for the pool. In other words, the tool lifts the floor and lowers the ceiling at the same time.',
      'Creativity is a skill. And like every skill, it needs to be trained.',
      'A study from MIT Media Lab pointed to the cost of skipping creativity training. Participants who wrote essays with an LLM showed the weakest brain connectivity of any group, remembered little of what they had just written, and felt little ownership over it. When they later wrote without the tool, the weaker engagement stayed with them. The researchers called it “cognitive debt.” Sadly, your creativity level does not come back the moment you stop enhancing it with the machine. In the same way, your garden will not grow flowers back the minute you stop harvesting them. Growing requires friction and struggle.',
      'Are you ready to struggle again, in the noble pursuit of escaping the average?',
    ],
  },
  {
    slug: 'essay-on-branding',
    title: 'Do I Have to Make Friends with Brands on Social Media to Buy Their Products?',
    subtitle: 'An essay on branding',
    date: 'May 24, 2014',
    source: 'https://www.slideshare.net/slideshow/br-35079115/35079115',
    sourceName: 'SlideShare',
    body: [
      { img: '/media/blog-branding-1.webp', caption: 'Coca-Cola sells not only fizzy drinks. It sells a philosophy of happiness and lifestyle.' },
      'Everyone knows what branding is. Or at least has a vague concept of what it means. Various trademarks twirling in front of your eyes. Different shapes, different colours. However, the idea remains the same: to glue a more or less successful icon onto stationery, often with a catchy slogan or a brand name.',
      'The first logos started to appear in ancient times. They rose from a real need for communication: an illiterate society had to learn to read symbols to function within the frame of the civilised world. Emblems represented different cities or ruling masters. Typically they consisted of torsos, sometimes of representations of trees, plants or geometrical shapes. As time went by, letters were added to those pictures. The purpose of the early graphic marks was to depict a substantial, given thing. The ancient designers did not have to create or invent the city or the rulers — there was no need for that. Cities and masters existed already. Every city had its own specific atmosphere, a recognizable vibe. Each ancient citizen could visit them and see them for what they were. Those personal sensations were transplanted from individual experiences onto the trademark. Graphic icons evoked memories of those visits. Small, simplified images comprised every detail of the city.',
      'Inventing identities has never been easy. But creating identities in a void is an even more difficult task. Nothing has the right to exist in a vacuum — even the most beautiful piece of graphic design. The fake can be sensed immediately and intuitively when there is no correlation between design and reality. I agree with Nick Bell (Eye Magazine 53, Autumn 2004) that a simple image has power. However, that power is not in the image itself. Since everyone can interpret images in their own way, that strength must be hidden in the semiotic — in layers of knowledge and experience accumulated throughout years of living. But because we all live in the same world and at the same time, an intelligent designer can try to guess what kind of trigger can be used to evoke a certain kind of response.',
      'Inescapably, and despite growing respect for regional traditions, our world is getting more and more homogeneous. International brands stand for the same values in different parts of the world. Take Coca-Cola, for example. The brand, originally derived from the United States, is now sold in over 200 countries around the world. Its website has a similar interface and graphics in every country, on every continent. The brand has coined the metaphor for drinking Coke: they claim that it is like tasting life, to the last drop. They linked a fizzy, sweet drink with happiness, and further — with music (which makes you happy). Under the red and white emblem they set up various music festivals. On their websites you can find sections about health, environment, community and the Olympic Games. You can calculate your BMI, read about sports events, make a cake based on one of the recipes found there, or make sure that by drinking a beverage you help set up new businesses in Africa. People around the world hold the same values, have similar worries and concerns. Happiness is an international asset. Hence the marketing policy of the Coca-Cola company is successful and understandable everywhere. In one memorable campaign they delivered happiness in Rio de Janeiro, Brazil, by red trucks. They deliver their positive philosophy, their translation of actuality. In the disguise of delivering happiness they are selling their products. Or maybe not? Perhaps their main aim is to deliver happiness, and products are sold just on the fly? Do they still remember that they sell drinks, and that they are not a non-profit charity organization? The Coca-Cola trademark, or even its branding colours, shown to a person who had never seen them before, would probably have no impact. But we — the majority of the human population — entirely like in Pavlov’s experiment with a dog, associate that symbol with a meticulously assigned meaning. How did this happen? Today over a hundred million people follow Coca-Cola on social media, making it one of the most-followed brands in the world — ahead of most of the pop stars whose songs play in its ads. What does it mean? Do I have to develop a positive emotional attitude towards certain brands just to buy the products they offer?',
      'We live in luxurious times. Nowadays most proprietary products reach high, comparable standards. Sometimes it is really hard to find veritable differences between items. According to one experiment, even genuine beer enthusiasts cannot tell which no-name glass holds their favourite type of amber nectar. Hoovers, washing machines, clocks, cameras — they are all rather good and fulfill their primary function pretty well. Since there is no real difference between products, that difference must be created. And here is a clear field for branding. The brands hidden behind articles have to distinguish themselves emotionally from each other. They have to fight for those “likes”, even on social networks. Brands must be iconic enough that I could crave them. They must be a little like a best friend, so that by interacting with them you could feel better. Sometimes their imaginary personality is so tempting that it might be adopted by users as their own — especially when our own personalities are not so unstained. In extreme cases people start grouping themselves into a sort of fan club, preaching a designed corporate philosophy as their own. Volcom, Burton, Apple, Nike, Levi’s, Coca-Cola, Red Bull… examples of brands with many zealous devotees seem to be endless.',
      { img: '/media/blog-branding-2.webp', caption: 'Nike consistently builds its corporate image as a very sporty company.' },
      'I completely disagree with Mr Bodkin’s point of view that branding is a backward approach to design — that the result of branding is a package that has nothing to do with the content. That may be true of wrongly designed corporate identities; human errors always took and will take place. But why should professionally done branding not have anything to do with content? I am absolutely convinced that the visual image of a company should mean exactly the same as its content means.',
      'According to Wally Olins, the acclaimed brand guru, new brands take character after their founder. To tell the truth, I agree with that statement fiercely. The logical reasoning is simple: the founder is a real person, with a real character and human traits. The people they employ are not just random — they were chosen by the founder carefully, so their personalities probably match up with his or her view of the company. We cannot forget that a business is framed by people, not by established mock rules or applied trademarks. It is framed by the way employees behave, look, talk, dress. Moreover, in many companies a customer’s opinion depends on their first contact with a particular brand, which is predominantly through its employees. Besides that, the prime contact is often established even without the presence of company workers, as happens in shops, for example. Hence I believe that people are an essential factor in the prosperity of a brand. Consequently, corporate identity is not unnatural. It is unaffectedly ingrained at the very beginning of every business. Most existing big corporations had great founders. They must have been very inspirational, exceptionally charismatic, with strong beliefs in their notion. Otherwise their firms would not have achieved such incredible success.',
      'To my mind, designing corporate identity should not be about creating a beautiful sign. It should emerge from the company itself. Nick Bell, in his article from Autumn 2004 published in Eye Magazine 53, points out a problematic issue in designing corporate identities for cultural institutions such as galleries and museums. He states that problems emerge “when the visual language and agenda of marketing, branding and promotion is employed at a curatorial, editorial level.” One major drawback of this approach is that he seems not to take into consideration that the origin of a museum or gallery is exactly the same as the origin of a company: they always have a founder. Moreover, it is most likely that every gallery or museum has a distinct, unrepeatable character. Those unique traits cannot just be covered by artificial, accidental graphics chosen in terms of aesthetics or personal taste. They should rather be found, and highlighted.',
      'There is always a possibility that the image of a museum, gallery or company could be better. In most cases it is true. However, from my point of view, visual artists are not responsible for fixing the corporate image. There are other specialists with better competences to do so, like PR experts or marketers. Nevertheless, graphic designers should work in close collaboration with them — sometimes their creative element might be very inspirational. I believe that a combination of science, knowledge, cleverness and novelty always brings the best results. Sometimes fixing corporate identity is not enough. In some cases — when it comes to mergers or changes in ownership, for example — the corporate image must be reinvented. But it should still be created on a solid, real basis. It must constitute a unity with everything that counts as the company. Corporate image is not designed only for customers. It has to do with everyone who interacts with a brand: workers, their families, customers, journalists, competitors, opinion leaders, people who post their judgements online… More important than the logo itself is the corporate philosophy and the values represented by the company. According to experiments on liking conducted by Ortony, Norman and Revelle in the United States, given regular exposure people can develop a taste for any logo. Vice versa, even the most beautiful and creative piece of graphic design, although it has a value in itself, cannot guarantee business success. Branding is not only about a logo. So what is it about?',
      { img: '/media/blog-branding-3.webp', caption: 'Famous women who were faces of cosmetic companies: Lancôme, L’Oréal, Max Factor, Gucci, Prada, Revlon.' },
      'It is my contention that brands are like people. They are outgrowths of human strains, of human dreams. Going this way, as Nick Bell rightly noticed, human relationships might be perceived as a model for brand identity design. To support this point of view I would like to point out what features people and brands have in common. First of all, they both have personalities. They can be described using the same adjectives: trustworthy, friendly, traditional, responsive, elegant, cool, modern, etc. Secondly, they influence us in exactly the same way we are influenced by other people. They affect our individualities. We take over their personality traits when we consider them cool. Sometimes they even teach us how to live, how to impress the people around us. I will not assess whether that is a positive or a negative phenomenon. It is just the way it is. People have always needed something or somebody to show them how to behave and what is right. In the past that was probably the church, or the king’s court… You could belong to some political party, or be a member of a hippy movement. Nowadays big corporations assume responsibility for doing so. As far as their policies are to preach happiness (as Coca-Cola does), to opt for a healthy and active lifestyle (Nike) or to learn, be curious and know more about the world (The Economist, The Guardian), I have just nothing against them.',
      'Furthermore, we can develop feelings towards brands, just like towards human beings. Often the only reason we do not put an article in our trolley is that we simply do not like the brand. There might be nothing wrong with the product; the whole climate surrounding the company just does not match our preferences. For example, if we are calm and quiet, we might not like brands we consider garish and noisy (like Dolce & Gabbana), for the same reasons we do not like noisy people or do not listen to noisy music.',
      'It is getting more and more popular for corporations to hire — within the frame of their marketing strategy — real, often famous people with recognizable personalities, just to represent them. It is quite tricky: in this way not only do ordinary humans take over personality traits from companies, but companies also take over features from the people they hire. That means average people take over characteristics from people who were chosen by marketing specialists working in companies. Corporations which want to be perceived as more active and sporting sponsor sportsmen who suit their corporate image. Those athletes have to sign very severe and detailed contracts — it is almost like selling their personalities to the brands. Cosmetic corporations are predominantly represented by beautiful (and stylish!) models or actresses. However, L’Oréal decided to build its image by creating a team of female scientists, to strengthen its corporate picture as a professional company with a solid science background.',
      'The intention of this essay is not to state that designing the visual image of a corporation is less important than it was in the past. My main aim is to emphasize the importance of building a coherent image of the corporation as a whole. Beautiful graphics are just one of many factors of future branding. When it is decided that a company really needs a logo in the traditional form, then possibly that is a good solution. But I encourage considering the second option too. Moreover, contemporary logos do not need to have only one fixed shape. They might be more fluid than they were in the past. Just take a closer look at the branding of Tate, Google, AOL… Those visual systems, despite having numerous different shapes of logotype, are still very consistent. I can tell one company’s stationery from another’s by the type of paper alone, even if there is no sign on it.',
      { img: '/media/blog-branding-4.webp', caption: 'A revolutionary approach to branding: various, coexisting versions of the Google logo.' },
      'I would like to avoid building corporate identity by sticking ill-assorted elements onto the surface of the brand. Work on branding should be started from the bottom, by answering some basic questions, such as: who are we, what do we do, and what do we want to become? That is it. To my mind, visual branding consists of literally everything that surrounds the company: the environment, the building where the company works, the chandelier in the main office, even the workers’ shoes. Creating corporate identity is becoming more like creating — or maybe even improving — a corporate personality. It cannot be based only on an artificial sign. The logo, however, might be the icing on the cake.',
      'Bibliography: Rosen, B. (1970) Corporate Search for Visual Identity; Fletcher, W. (2008) Powers of Persuasion; Aldersey-Williams, H. (1994) Corporate Identity; Marchand, R. (1998) Creating the Corporate Soul; Peters, R. (2005) Worldwide Identity; Franzen, G. (1999) Brands & Advertising; Olins, W. & Selame, E. (2000) International Corporate Identity Handbook; Olins, W. (1995) International Corporate Identity; Olins, W. (1978) Corporate Personality; Bell, N. (2004) “The Steamroller of Branding”, Eye Magazine 53; Bell, N. (2006–2008) writings on design and identity; Cialdini, R. (2004); Sumodesign (2010) Insight — Branding Issue.',
    ],
  },
];

export function Blog({ openPost }) {
  return <main className="editorial-page">
    <div className="blog-row">
      <div className="post-list">
        {posts.map((post) => <React.Fragment key={post.slug}>
          <button className="post-card" onClick={() => openPost(post.slug)}>
            <span className="post-card-date">{post.date}</span>
            <span className="post-card-title">{post.title}</span>
            <span className="post-card-sub">{post.subtitle}</span>
            <ChevronRight className="post-card-chevron" aria-hidden="true" />
          </button>
          {post.slug === 'escaping-the-average' && <aside className="blog-reel">
            <video
              src={`${import.meta.env.BASE_URL}media/insta-reel-homogenity.mp4`}
              poster={`${import.meta.env.BASE_URL}media/insta-reel-homogenity-poster.jpg`}
              controls playsInline preload="metadata" />
          </aside>}
        </React.Fragment>)}
      </div>
    </div>
  </main>;
}

export function BlogPost({ post, close }) {
  const tr = useT();
  return <main className="case post">
    <button className="case-back" onClick={close}><ArrowLeft /> {tr('All posts', 'Alle Artikel')}</button>
    <section className="case-title post-title">
      <p>{post.date} · {post.subtitle}</p>
      <h1>{post.title}</h1>
    </section>
    <div className="post-body">
      {post.body.map((item, i) => typeof item === 'string'
        ? <p key={i}>{item}</p>
        : <figure className="post-figure" key={i}>
            <img src={import.meta.env.BASE_URL + item.img.replace(/^\//, '')} alt={item.caption} loading="lazy" />
            <figcaption>{item.caption}</figcaption>
          </figure>)}
    </div>
    <a className="post-source" href={post.source} target="_blank" rel="noreferrer">
      {tr(`Originally published on the ${post.sourceName}`, `Ursprünglich erschienen: ${post.sourceName}`)} <ArrowUpRight />
    </a>
  </main>;
}
